

services:
  web:
    image: httpd:latest  # Apache HTTP Server image
    ports:
      - "4444:80"  # Expose Apache on port 4444
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./html:/usr/local/apache2/htdocs/  # Mounting HTML files to Apache's document root

  db:
    image: mysql:latest  # MySQL database image
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"  # Expose MySQL on port 3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
