

services:
  web:
    image: nginx:latest  # Replace with your preferred web server image
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./html:/usr/share/nginx/html  # Mounting HTML files

  db:
    image: mysql:latest  # Replace with your preferred database image
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
